wrap code into functions

diff --git a/git-swash b/git-swash
--- a/git-swash
+++ b/git-swash
@@ -1,156 +1,214 @@
 #!/bin/bash
 
-# Exit if a command returns a non-zero exit code
-set -euo pipefail
+######################################## SET VALUES ###########################################
+readonly TRUE=0
+readonly FALSE=1
+readonly TEXT_RED='\033[0;31m'
+readonly TEXT_GREEN='\033[0;32m'
+readonly TEXT_YELLOW='\033[0;33m'
+readonly TEXT_BLUE='\033[0;34m'
+readonly TEXT_NC='\033[0m'
+readonly BACKGROUND_YELLOW=$'\e[43;5;33m'
+readonly BACKGROUND_BLUE=$'\e[48;5;33m'
+readonly BACKGROUND_NC=$'\e[0m'
+readonly HIGHLIGHT_YELLOW=$'\e[1;33m' 
+readonly HIGHLIGHT_NC=$'\e[0;0m'
 
-# Set ANSI escape codes for text formatting
-RED='\033[0;31m'
-GREEN='\033[0;32m'
-BLUE='\033[0;34m'
-NC='\033[0m'
 
-# Define the color codes
-HIGHLIGHT_YELLOW=$'\e[1;33m' 
-HIGHLIGHT_NC=$'\e[0;0m'
 
-# Helper function to check for unsaved changes in the working directory
-function unsaved_files {
-    local files=$(git diff-index HEAD) || true
-    if [[ -n "$files" ]]; then
-        printf 'true\n'
+######################################### HELPERS ##############################################
+
+# Find and return branches
+function find_branches {
+    local _target="$1"
+    local _branches=($(git branch -ila "*$_target*")) || true  # Find branches with similar name
+
+    # Exit script if no matching branches are found
+    if [[ ${#_branches[@]} -eq 0 ]]; then
+        echo -e "${TEXT_RED}Error${TEXT_NC}: No branches found matching the name ${TEXT_YELLOW}$_target${TEXT_NC}"
+        exit $FALSE
+    fi
+
+    echo "${_branches[@]}"
+}
+
+function find_branch_stash {
+    local _branch="$1"
+    while IFS= read -r line; do
+        _stash_list+=("$line")
+    done < <(git stash list | grep "$_branch")
+
+    # Exit script if no stashes
+    if [[ ${#_stash_list[@]} -eq 0 ]]; then
+        exit $TRUE
+    fi
+
+    echo "${_stash_list[@]}"
+}
+
+# Return whether there are unsaved changes in the working directory
+function are_unsaved_files_present {
+    local _files=$(git diff-index HEAD) || true 
+    if [[ -n "$_files" ]]; then
+        return $TRUE
     else
-        printf 'false\n'
+        return $FALSE
+    fi
+}
+
+function handle_unsaved_file {
+    are_unsaved_files_present
+    if [[ $? -eq $TRUE ]]; then
+        read -rp "There are unsaved changes in the working directory. Stash (s), commit (c) or ignore (i)? : " answer
+        case "$answer" in
+            stash|[sS])
+                git stash save "stash for $(git rev-parse --abbrev-ref HEAD)" || exit 1
+                printf 'Unsaved changes have been stashed.\n';;
+            commit|[cC])
+                read -rp "Please provide a commit message: " commit_message
+                git add . || exit 1
+                git commit -m "$commit_message" || exit 1
+                printf 'Unsaved changes have been committed with message: %s\n' "$commit_message";;
+            ignore|[iI])
+                git reset --hard HEAD || exit 1;;
+            *)
+                printf 'Invalid option. No changes were made.\n'
+                exit 1;;
+        esac
+    fi
+}
+
+# Return array with higlighted elements
+function prepare_options {
+    local _options=("$@")                         # convert function arguments to array
+    local _target=${_options[${#_options[@]}-1]}  # last element of array is the target keyword
+    local _result=()                              # create a new array for the results
+    unset '_options[${#_options[@]}-1]'           # remove keyword from array of options
+
+    local _lower=$(echo "$_target" | tr '[:lower:]' '[:upper:]')
+    local _upper=$(echo "$_target" | tr '[:upper:]' '[:lower:]' )
+    # Loop over each element in the array and perform a case-insensitive comparison
+    for _option in "${_options[@]}"; do
+        #TODO::if option is current branch color it in green
+        if [[ "$_option" =~ ${_lower} ]]; then
+            _result+=("${_option/$_lower/$'${BACKGROUND_YELLOW}$_lower${BACKGROUND_NC}'}") #highlight the given keyword
+        else
+            _result+=("${_option/$_upper/$'${BACKGROUND_YELLOW}$_upper${BACKGROUND_NC}'}") #highlight the given keyword
+        fi
+    done
+
+    echo "${_result[@]}"
+}
+
+function select_option {
+    local _options=("$@")
+    if [[ ${#_options[@]} -gt 1 ]]; then
+        select _option in "${_options[@]}"; do
+            if [[ "${_options[@]}" =~ "${_option}" ]]; then     # Whether selected option is in the list of options
+                break
+            else
+                echo "Invalid option. Please select a valid option."
+            fi
+        done
+    elif [[ ${#_options[@]} -eq 1 ]]; then
+        _option=${_options[0]}
+    else
+        exit 1;
+    fi
+
+    echo "${_option}"
+}
+
+# Removes any occurrences of the HIGHLIGHT_YELLOW and HIGHLIGHT_NC escape sequences from the target
+function remove_highlight {
+    local _target="$1"
+    _target=${_target/${BACKGROUND_YELLOW}}
+    _target=${_target/${BACKGROUND_NC}}
+
+    echo "$_target"
+}
+
+function swich_to {
+    local _branch="$1"  
+    git checkout "${_branch}" || exit $FALSE; 
+    printf 'Checked out to branch %s.\n' "$_branch"
+}
+
+function handle_stash {
+    local _target="$1"
+
+    while IFS= read -r line; do
+        _stash_list+=("$line")
+    done < <(git stash list | grep "$_target")
+
+    # Pop if only one stash
+    if [ ${#_stash_list[@]} -eq 1 ]; then
+        local _stash=${_stash_list[0]%%:*}                                     # remove evetying after first `:`
+        local _index=$(echo "$_stash" | sed -nE 's/stash@\{([0-9]+)\}/\1/p')   # parse stash index
+        git stash pop --index "${_index}"
+    fi
+
+    # Select if more then one
+    if [ ${#_stash_list[@]} -gt 1 ]; then
+        echo -e "${TEXT_BLUE} Multiple stash records detected (0 for exit): ${TEXT_NC}"
+        local _options=()
+        local _lower=$(echo "$_target" | tr '[:lower:]' '[:upper:]')
+        local _upper=$(echo "$_target" | tr '[:upper:]' '[:lower:]' )
+        #TODO:: use prepare_options
+        for _option in "${_stash_list[@]}"; do
+            if [[ "$_option" =~ ${_target} ]]; then
+                _options+=("${_option/$_target/$'${BACKGROUND_YELLOW}$_target${HIGHLIGHT_NC}'}")
+            elif [[ "$_option" =~ ${_lower} ]]; then
+                _options+=("${_option/$_lower/$'${BACKGROUND_YELLOW}$_lower${HIGHLIGHT_NC}'}")
+            else
+                _options+=("${_option/$_upper/$'${BACKGROUND_YELLOW}$_upper${HIGHLIGHT_NC}'}")
+            fi
+        done
+
+        select _option in "${_options[@]}"; do
+            if [[ -n $_option ]]; then
+                local _stash=${_option%%:*}                                             # remove evetying after first `:`
+                local _index=$(echo "$_stash" | sed -nE 's/stash@\{([0-9]+)\}/\1/p')    # parse stash index 
+                git stash pop --index "${_index}"
+                break
+            else
+                exit $TRUE;
+                break
+            fi
+        done
     fi
 }
 
 
-######## SELECT BRANCH ############
+
+################################################ START ####################################################
 
 # Exit script if no branch name is provided
 if [[ -z "${1:-}" ]]; then
     printf 'Error: Please specify a branch name.\n'
-    exit 1
+    exit $FALSE
 fi
 
 target="$1"
-
-# Find branches with similar name
-branch_list=($(git branch -ila "*$target*")) || true
-
-# Exit script if no matching branches are found
-if [[ ${#branch_list[@]} -eq 0 ]]; then
-    printf 'Error: No branches found matching the name %s.\n' "$target"
-    exit 1
+# Find all branches
+#TODO::swich immidiatly if exact match find
+branches=($(find_branches "$target" ))
+# validate
+if [[ $? -eq $FALSE ]]; then
+    exit $FALSE
 fi
-
-branches=()
-target_lower=$(echo "$target" | tr '[:lower:]' '[:upper:]')
-target_upper=$(echo "$target" | tr '[:upper:]' '[:lower:]' )
-# Loop over each element in the array and perform a case-insensitive comparison
-for branch in "${branch_list[@]}"; do
-    if [[ "$branch" =~ ${target_lower} ]]; then
-        branches+=("${branch/$target_lower/$'${HIGHLIGHT_YELLOW}$target_lower${HIGHLIGHT_NC}'}")
-    else
-        branches+=("${branch/$target_upper/$'${HIGHLIGHT_YELLOW}$target_upper${HIGHLIGHT_NC}'}")
-    fi
-done
-
-# Loop through branches and highlight the given keyword
-# branches=("${branches[@]/$target/$'${HIGHLIGHT_YELLOW}$target${HIGHLIGHT_NC}'}")
 
 # Select the needed branch
-if [[ ${#branches[@]} -gt 1 ]]; then
-    PS3="Select a branch option: "
-    select branch in "${branches[@]}"; do
-    # Check if the selected option is in the list of available options
-    if [[ " ${branches[@]} " =~ " ${branch} " ]]; then
-        break
-    else
-        echo "Invalid option. Please select a valid option."
-    fi
-done
-else
-    branch=${branches[0]}
-fi
+options=($(prepare_options "${branches[@]}" "$target" ))
+option=($(select_option "${options[@]}"))
+branch=$(remove_highlight "$option")
 
-# Remove color codes from the selceted branch
-branch=${branch/${HIGHLIGHT_YELLOW}}
-branch=${branch/${HIGHLIGHT_NC}}
-
-# Checkout unsaved changes
-if unsaved_files | grep -q '^true$'; then
-    read -rp "There are unsaved changes in the working directory. Stash (s), commit (c) or ignore (i)? : " answer
-    case "$answer" in
-        stash|[sS])
-            git stash save "stash for $(git rev-parse --abbrev-ref HEAD)" || exit 1
-            printf 'Unsaved changes have been stashed.\n';;
-        commit|[cC])
-            read -rp "Please provide a commit message: " commit_message
-            git add . || exit 1
-            git commit -m "$commit_message" || exit 1
-            printf 'Unsaved changes have been committed with message: %s\n' "$commit_message";;
-        ignore|[iI])
-            git reset --hard HEAD || exit 1;;
-        *)
-            printf 'Invalid option. No changes were made.\n'
-            exit 1;;
-    esac
-fi
-
-# Make sure a branch is selected
+# validate
 if [[ -z "${branch:-}" ]]; then
     printf 'Error: No branch selected.\n'
-    exit 1
+    exit $FALSE
 fi
 
-echo "$branch"
-git checkout "${branch}" || exit 1
-printf 'Checked out to branch %s.\n' "$branch"
-
-
-
-
-######## SELECT STASH ############
-#TODO:: make it less ugly
-
-# Check for stashes with the current branch
-declare -a stash_list
-while IFS= read -r line; do
-    stash_list+=("$line")
-done < <(git stash list | grep "$branch")
-
-# Pop if only one stash
-if [ ${#stash_list[@]} -eq 1 ]; then
-    # remove evetying after first `:`
-    stash=${stash_list[0]%%:*}
-    #get stash index
-    index=$(echo "$stash" | sed -nE 's/stash@\{([0-9]+)\}/\1/p')
-    git stash pop --index "${index}"
-fi
-
-
-# Select if more then one
-if [ ${#stash_list[@]} -gt 1 ]; then
-    stashes=()
-    # Loop over each element in the array and perform a case-insensitive comparison
-    for stash in "${stash_list[@]}"; do
-        if [[ "$stash" =~ ${target_lower} ]]; then
-            stashes+=("${stash/$target_lower/$'${HIGHLIGHT_YELLOW}$target_lower${HIGHLIGHT_NC}'}")
-        else
-            stashes+=("${stash/$target_upper/$'${HIGHLIGHT_YELLOW}$target_upper${HIGHLIGHT_NC}'}")
-        fi
-    done
-
-    PS3="Select an stash option to pop: "
-    select stash in "${stashes[@]}"; do
-        if [[ -n $stash ]]; then
-            # remove evetying after first `:`
-            stash=${stash%%:*}
-            index=$(echo "$stash" | sed -nE 's/stash@\{([0-9]+)\}/\1/p') 
-            git stash pop --index "${index}"
-            break
-        else
-            echo "Invalid selection. Please choose again."
-        fi
-    done
-fi
+handle_unsaved_file
+swich_to "${branch}"
+handle_stash "${branch}"
