Add stash selection

diff --git a/git-swash b/git-swash
--- a/git-swash
+++ b/git-swash
@@ -13,7 +13,6 @@ NC='\033[0m'
 HIGHLIGHT_YELLOW=$'\e[1;33m' 
 HIGHLIGHT_NC=$'\e[0;0m'
 
-
 # Helper function to check for unsaved changes in the working directory
 function unsaved_files {
     local files=$(git diff-index HEAD) || true
@@ -24,6 +23,9 @@ function unsaved_files {
     fi
 }
 
+
+######## SELECT BRANCH ############
+
 # Exit script if no branch name is provided
 if [[ -z "${1:-}" ]]; then
     printf 'Error: Please specify a branch name.\n'
@@ -33,10 +35,10 @@ fi
 target="$1"
 
 # Find branches with similar name
-_branches=($(git branch -ila "*$target*")) || true
+branch_list=($(git branch -ila "*$target*")) || true
 
 # Exit script if no matching branches are found
-if [[ ${#_branches[@]} -eq 0 ]]; then
+if [[ ${#branch_list[@]} -eq 0 ]]; then
     printf 'Error: No branches found matching the name %s.\n' "$target"
     exit 1
 fi
@@ -45,7 +47,7 @@ branches=()
 target_lower=$(echo "$target" | tr '[:lower:]' '[:upper:]')
 target_upper=$(echo "$target" | tr '[:upper:]' '[:lower:]' )
 # Loop over each element in the array and perform a case-insensitive comparison
-for branch in "${_branches[@]}"; do
+for branch in "${branch_list[@]}"; do
     if [[ "$branch" =~ ${target_lower} ]]; then
         branches+=("${branch/$target_lower/$'${HIGHLIGHT_YELLOW}$target_lower${HIGHLIGHT_NC}'}")
     else
@@ -95,37 +97,60 @@ if unsaved_files | grep -q '^true$'; then
     esac
 fi
 
-git checkout "${branch}" || exit 1
-printf 'Checked out to branch %s.\n' "$branch"
-
 # Make sure a branch is selected
 if [[ -z "${branch:-}" ]]; then
     printf 'Error: No branch selected.\n'
     exit 1
 fi
 
+echo "$branch"
+git checkout "${branch}" || exit 1
+printf 'Checked out to branch %s.\n' "$branch"
+
+
+
+
+######## SELECT STASH ############
+#TODO:: make it less ugly
+
 # Check for stashes with the current branch
-stash_list=($(git stash list | grep "$branch")) || true
+declare -a stash_list
+while IFS= read -r line; do
+    stash_list+=("$line")
+done < <(git stash list | grep "$branch")
 
-# Loop through stashes and highlight the selected branch
-stash_list=("${stash_list/$branch/$'${HIGHLIGHT_YELLOW}$branch${HIGHLIGHT_NC}'}")
-
-# Select the needed stash
-if [ ${#stash_list[@]} -gt 0 ]; then
-    echo -e "The following stashes were found for the current branch ${GREEN}$branch${NC}"
-    git stash list | grep "$branch"
+# Pop if only one stash
+if [ ${#stash_list[@]} -eq 1 ]; then
+    # remove evetying after first `:`
+    stash=${stash_list[0]%%:*}
+    #get stash index
+    index=$(echo "$stash" | sed -nE 's/stash@\{([0-9]+)\}/\1/p')
+    git stash pop --index "${index}"
 fi
 
-#if [ ${#stash_list[@]} -ge 1 ]; then
-#    echo "The following stashes were found for the current branch ($branch):"
-#    select stash in "${stash_list[@]}"; do
-#        break
-#    done
-#
-#    read -p "Do you want to pop the stash? (y/n) " answer
-#    if [ "$answer" == "y" ]; then
-#        # Pop the stash
-#        git stash pop
-#        echo "Stash has been popped."
-#    fi
-#fi
+
+# Select if more then one
+if [ ${#stash_list[@]} -gt 1 ]; then
+    stashes=()
+    # Loop over each element in the array and perform a case-insensitive comparison
+    for stash in "${stash_list[@]}"; do
+        if [[ "$stash" =~ ${target_lower} ]]; then
+            stashes+=("${stash/$target_lower/$'${HIGHLIGHT_YELLOW}$target_lower${HIGHLIGHT_NC}'}")
+        else
+            stashes+=("${stash/$target_upper/$'${HIGHLIGHT_YELLOW}$target_upper${HIGHLIGHT_NC}'}")
+        fi
+    done
+
+    PS3="Select an stash option to pop: "
+    select stash in "${stashes[@]}"; do
+        if [[ -n $stash ]]; then
+            # remove evetying after first `:`
+            stash=${stash%%:*}
+            index=$(echo "$stash" | sed -nE 's/stash@\{([0-9]+)\}/\1/p') 
+            git stash pop --index "${index}"
+            break
+        else
+            echo "Invalid selection. Please choose again."
+        fi
+    done
+fi
